$env:BD_ACTOR='deacon'
$env:BD_BACKUP_ENABLED='false'
$env:BEADS_DOLT_AUTO_START='0'
$env:BEADS_DOLT_PORT='3307'
$env:CLAUDECODE=''
$env:CLAUDE_CODE_EFFORT_LEVEL='high'
$env:GIT_AUTHOR_NAME='deacon'
$env:GIT_CEILING_DIRECTORIES='D:\Users\kapo_\Documents\github\lucky5-v8\lucky5-v8'
$env:GT_AGENT='claude'
$env:GT_DOLT_PORT='3307'
$env:GT_PROCESS_NAMES='claude.exe'
$env:GT_ROLE='deacon'
$env:GT_ROOT='D:\Users\kapo_\Documents\github\lucky5-v8\lucky5-v8'
$env:GT_SESSION='hq-deacon'
$env:GT_SESSION_ID_ENV='CLAUDE_SESSION_ID'
$env:NODE_OPTIONS=''
& D:\ProgramData\chocolatey\bin\claude.exe --dangerously-skip-permissions '[GAS TOWN] deacon <- daemon • 2026-10-04T05:55 • patrol

I am Deacon. Start patrol: run gt deacon heartbeat, then check gt hook. If no hook, run gt sling mol-deacon-patrol deacon, then execute the hook it creates.'
